Repository Eco-Friends-Connect/Eco-Friends, pull requests merged in 2024-08, with the labels that each got.

#108 Connect signup
  backend/docs/swagger.json
  backend/models/signups.js
  backend/models/volunteer_request.js
  backend/package.json
  backend/src/api/get-api.js
  backend/src/api/post-api.js
  backend/src/server.js
  src/component/eco-form/eco-form.jsx
  src/pages/org-dashboard/org-dashboard.jsx
Labels: Frontend, Backend

#111 Search results
  src/component/event-list/Event-Card.jsx
  src/component/event-list/Event-List.jsx
  src/component/event-list/EventCard.module.scss
  src/pages/VolunteerSearch.jsx
  src/pages/VolunteerSearch.module.scss
Labels: enhancement

#115 Loginconnect
  backend/models/signups.js
  backend/src/api/post-api.js
  src/component/login-form/Loginform.jsx
  src/component/search-bar/search_bar.module.scss
Labels: enhancement

#130 homepage responsiveness fixed
  src/component/footer/Footer.jsx
  src/component/footer/footer.module.scss
  src/component/navbar/navbar.module.scss
  src/pages/home/Home.module.scss
Labels: Frontend

#132 about of the creator page done
  src/component/creator/creator.jsx
  src/component/creator/creator.module.scss
Labels: Frontend

#137 about page responds to small devices
  src/component/creator/creator.module.css
  src/component/creator/creator.module.css.map
  src/component/creator/creator.module.scss
  src/component/description/AboutTheSiteText.module.css
  src/component/description/AboutTheSiteText.module.css.map
  src/component/description/AboutTheSiteText.module.scss
  src/component/description/about-the-site-text.jsx
  src/component/event-list/EventCard.module.css
  src/component/event-list/EventCard.module.css.map
  src/component/footer/footer.module.css
  src/component/footer/footer.module.css.map
  src/component/login-form/Login.module.css
  src/component/login-form/Login.module.css.map
  src/component/navbar/navbar.module.css
  src/component/navbar/navbar.module.css.map
  src/component/search-bar/search_bar.module.css
  src/component/search-bar/search_bar.module.css.map
  src/component/signup-form/Signup.module.css
  src/component/signup-form/Signup.module.css.map
  src/pages/VolunteerSearch.module.css
  src/pages/VolunteerSearch.module.css.map
  src/pages/badges-page/badges-page.module.css
  src/pages/badges-page/badges-page.module.css.map
  src/pages/events-page/events-page.module.css
  src/pages/events-page/events-page.module.css.map
  src/pages/home/Home.module.css
  src/pages/home/Home.module.css.map
  src/pages/login-page/login-page.module.css
  src/pages/login-page/login-page.module.css.map
  src/pages/userororgpage/UserOrOrgPage.module.css
  src/pages/userororgpage/UserOrOrgPage.module.css.map
Labels: Frontend

#148 Can now add Image to badges 🙂
  .github/ISSUE_TEMPLATE/config.yml
  backend/src/api/post-api.js
  src/component/eco-form/eco-form.jsx
  src/component/event-list/Event-Card.jsx
  src/pages/VolunteerSearch.jsx
  src/pages/badges-page/badges-page.jsx
  src/pages/check-participant/check-participant.jsx
  src/pages/org-dashboard/org-dashboard.jsx
Labels: bug, Frontend, Backend

#158 Feature: Added Docker & installed `npm` packages
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .gitignore
  backend/.dockerignore
  backend/Dockerfile
  backend/package.json
  backend/src/server.js
  firebase.json
  src/config.js
Labels: Backend

#159 returning and displaying firebase error messages to the user & additi…
  backend/src/api/post-api.js
  src/component/signup-form/Signup.jsx
  src/component/signup-form/Signup.module.css
  src/component/signup-form/Signup.module.scss
  src/pages/SignupForm.jsx
Labels: bug

#161 bug fix and added functionality to homepage buttons
  src/App.jsx
  src/pages/home/Home.jsx
Labels: bug

#178 Org styling
  .github/workflows/firebase-hosting-merge.yml
  .gitignore
  src/App.css
  src/App.jsx
  src/App.scss
  src/component/navbar/navbar.module.css
  src/component/navbar/navbar.module.scss
  src/component/user/user.jsx
  src/component/user/user.module.css
  src/component/user/user.module.scss
  src/pages/UserPage.jsx
  styles/variables.scss
Labels: Frontend

#173 Loginnav
  package.json
  src/component/navbar/Navbar.jsx
  src/component/navbar/Navbar.test.jsx
  src/component/welcome-logout/WelcomeLogout.jsx
  src/component/welcome-logout/WelcomeLogout.module.css
  src/component/welcome-logout/WelcomeLogout.module.scss
  src/pages/UserPage.jsx
  src/pages/home/Home.jsx
  src/pages/org-dashboard/org-dashboard.jsx
Labels: Design
