Repository Eco-Friends-Connect/Eco-Friends, pull requests merged in 2024-07, with the labels that each got.

#25 SignUp Form
  src/component/Signup.jsx
  src/component/Signup.module.css
Labels: enhancement

#27 Navbar
  package.json
  src/App.jsx
  src/component/Navbar.jsx
  src/component/navbar.module.css
  src/index.css
  src/package.json
  src/pages/AboutTheCreators.jsx
  src/pages/AboutTheSite.jsx
  src/pages/Eco-Chat.jsx
  src/pages/Home.jsx
  src/pages/LearderBoard.jsx
  src/pages/OrgLogin.jsx
  src/pages/UserPage.jsx
  src/pages/VolunteerSearch.jsx
Labels: enhancement

#26 feature: Added Search bar
  index.html
  package.json
  src/App.css
  src/component/Navbar.jsx
  src/component/Signup.jsx
  src/component/Signup.module.scss
  src/component/navbar.module.scss
  src/component/search_bar.jsx
  src/component/search_bar.module.scss
  src/index.css
  src/main.jsx
  styles/styles.scss
Labels: enhancement

#33 About the site Body with text boxes
  package.json
  src/component/AboutTheSiteText.module.scss
  src/component/AbouttheSiteText.jsx
  src/pages/AboutTheSite.jsx
Labels: enhancement

#34 added calendar component
  package.json
  src/component/SmallCalendar.jsx
  src/pages/UserPage.jsx
Labels: enhancement

#36 Docs: Added Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/code-adjustment.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#35 Feature: Added backend & connected to MongoDB
  .gitignore
  backend/models/orgEvent.js
  backend/models/orgLocation.js
  backend/models/organization.js
  backend/models/user.js
  backend/src/api/org_api.js
  backend/src/api/user_api.js
  backend/src/config.js
  backend/src/server.js
  package.json
Labels: enhancement

#41 Feature: Added rules for linting
  .eslintignore
  .eslintrc.cjs
  .github/workflows/lint.yml
  backend/models/badge.js
  backend/models/event.js
  backend/models/location.js
  backend/models/membership.js
  backend/models/org_event.js
  backend/models/signups.js
  backend/models/user.js
  backend/src/api/post-api.js
  backend/src/server.js
  docs/index.md
  docs/namingRules.md
  package.json
  src/App.jsx
  src/component/Navbar.jsx
  src/component/Signup.jsx
  src/component/SmallCalendar.jsx
  src/component/about-the-site-text.jsx
  src/component/search_bar.jsx
  src/main.jsx
  src/pages/AboutTheCreators.jsx
  src/pages/AboutTheSite.jsx
  src/pages/Eco-Chat.jsx
  src/pages/Home.jsx
  src/pages/LearderBoard.jsx
  src/pages/OrgLogin.jsx
  src/pages/UserPage.jsx
  src/pages/VolunteerSearch.jsx
Labels: documentation, enhancement

#50 Bugfix: Added mongoDB name
  .github/workflows/lint.yml
  backend/src/api/post-api.js
  backend/src/config.js
  backend/src/server.js
  package.json
Labels: bug, enhancement

#37 Added footer
  src/App.jsx
  src/component/Footer.jsx
  src/component/footer.module.scss
  src/pages/SiteSponsors.jsx
Labels: enhancement

#62 Feature: Added select option component & button
  src/App.jsx
  src/component/button/button.jsx
  src/component/button/button.module.scss
  src/component/description/AboutTheSiteText.module.scss
  src/component/description/about-the-site-text.jsx
  src/component/footer/Footer.jsx
  src/component/footer/footer.module.scss
  src/component/navbar/Navbar.jsx
  src/component/navbar/navbar.module.scss
  src/component/search-bar/search_bar.jsx
  src/component/search-bar/search_bar.module.scss
  src/component/select-option/select-option.jsx
  src/component/select-option/select-option.module.scss
  src/component/signup-form/Signup.jsx
  src/component/signup-form/Signup.module.scss
  src/pages/AboutTheSite.jsx
Labels: Design, Frontend

#66 Page assembly
  backend/src/api/post-api.js
  src/App.jsx
  src/component/description/AboutTheSiteText.module.scss
  src/component/description/about-the-site-text.jsx
  src/component/navbar/Navbar.jsx
  src/component/search-bar/search_bar.module.scss
  src/component/signup-form/Signup.jsx
  src/component/signup-form/Signup.module.scss
  src/pages/AboutTheSite.jsx
  src/pages/Eco-Chat.jsx
  src/pages/Home.jsx
  src/pages/Home.module.scss
  src/pages/LeaderBoard.jsx
  src/pages/NotFound.jsx
  src/pages/SignupForm.jsx
  src/pages/VolunteerSearch.jsx
Labels: enhancement

#76 Shaped buttons
  src/component/badge-form/badge-form.jsx
  src/component/button/button.jsx
  src/component/button/button.module.css
  src/component/button/button.module.css.map
  src/component/button/button.module.scss
  styles/styles.scss
  styles/variables.css
  styles/variables.css.map
  styles/variables.scss
Labels: enhancement, Design, Frontend

#83 User org select
  src/App.jsx
  src/assets/userWithoutCal.svg
  src/component/Calendar.jsx
  src/component/eco-button/eco-button.jsx
  src/component/select-option/select-option.jsx
  src/component/select-option/select-option.module.scss
  src/component/signup-form/Signup.jsx
  src/component/signup-form/Signup.module.scss
  src/pages/SignupForm.jsx
  src/pages/UserOrOrgPage.jsx
Labels: enhancement

#84 navbar update and css bugfix to show all of calendar
  src/component/navbar/Navbar.jsx
  src/component/signup-form/Signup.module.scss
  src/pages/org-login/OrgLogin.jsx
Labels: Design

#93 Feature,Bugfix: Added render tests
  .eslintignore
  .eslintrc.cjs
  .github/workflows/component.yml
  package.json
  src/App.jsx
  src/component/Calendar.jsx
  src/component/badge-form/badge-form.jsx
  src/component/badge-form/badge-form.test.jsx
  src/component/creator/creator.jsx
  src/component/creator/creator.module.css
  src/component/creator/creator.module.css.map
  src/component/creator/creator.test.jsx
  src/component/description/about-the-site-text.jsx
  src/component/description/about-the-site-text.test.jsx
  src/component/eco-button/eco-button.jsx
  src/component/eco-button/eco-button.test.jsx
  src/component/event-form/event-form.jsx
  src/component/event-form/event-form.test.jsx
  src/component/footer/Footer.jsx
  src/component/footer/Footer.test.jsx
  src/component/navbar/Navbar.jsx
  src/component/navbar/Navbar.test.jsx
  src/component/search-bar/search-bar.test.jsx
  src/component/search-bar/search_bar.jsx
  src/component/select-option/select-option.jsx
  src/component/select-option/select-option.module.css
  src/component/select-option/select-option.module.css.map
  src/component/select-option/select-option.test.jsx
  src/component/signup-form/Signup.jsx
  src/component/signup-form/Signup.module.css
  src/component/signup-form/Signup.module.css.map
  src/component/signup-form/Signup.test.jsx
  src/component/user/user.jsx
  src/component/user/user.test.jsx
  src/pages/AboutTheCreators.jsx
  src/pages/AboutTheSite.jsx
  src/pages/Eco-Chat.jsx
  src/pages/LeaderBoard.jsx
  src/pages/NotFound.jsx
  src/pages/SignupForm.jsx
  src/pages/SiteSponsors.jsx
  src/pages/UserOrOrgPage.jsx
  src/pages/UserPage.jsx
  src/pages/VolunteerSearch.jsx
  src/pages/home/Home.jsx
  src/pages/org-dashboard/org-dashboard.jsx
  src/pages/org-login/OrgLogin.jsx
  vitest.config.js
Labels: Frontend
